FROM nginx:alpine

RUN apk add --no-cache openssl && \
    mkdir -p /etc/nginx/certs && \
    openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
      -keyout /etc/nginx/certs/selfsigned.key \
      -out /etc/nginx/certs/selfsigned.crt \
      -subj "/C=SG/ST=Singapore/L=Singapore/O=SIT/OU=ICT/CN=127.0.0.1"

COPY nginx.conf /etc/nginx/conf.d/default.conf
